# See here for image contents: https://github.com/microsoft/vscode-dev-containers/tree/v0.202.5/containers/ubuntu/.devcontainer/base.Dockerfile

# [Choice] Ubuntu version (use hirsuite or bionic on local arm64/Apple Silicon): hirsute, focal, bionic
ARG VARIANT="hirsute"
FROM mcr.microsoft.com/vscode/devcontainers/base:0-${VARIANT}

# ** [Optional] Uncomment this section to install additional packages. **
RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install --no-install-recommends \
    wget iproute2 procps lsb-release


ARG UCM_DIR=/opt/unison-language
ARG UCM_ARCHIVE_NAME=ucm-linux.tar.gz
ARG UCM_ARCHIVE_URL=https://github.com/unisonweb/unison/releases/download/latest/$UCM_ARCHIVE_NAME

RUN mkdir -p $UCM_DIR \
    && wget -P $UCM_DIR $UCM_ARCHIVE_URL \
    && tar -C $UCM_DIR -xzf $UCM_DIR/$UCM_ARCHIVE_NAME \
    && ln -s $UCM_DIR/ucm /usr/bin/ \
    && rm $UCM_DIR/$UCM_ARCHIVE_NAME
